name: Build .deb package

on:
  workflow_call: {}

  workflow_dispatch:

jobs:
  build-deb:
    name: Build Debian packages
    runs-on: ubuntu-latest
    container: ubuntu:12.12
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu]
      fail-fast: false

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install base system dependencies
        run: |
          apt-get update
          apt-get install -y build-essential pkg-config curl ca-certificates git libssl-dev dpkg-dev gzip

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup toolchain install stable
          rustup default stable

      - name: Generate Man Page gzip
        run: gzip -fk doc/rgrc.1

      - name: Install cargo-deb
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo install --locked cargo-deb

      - name: Build project and generate deb for target
        env:
          PREFIX: /usr/local
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo deb --target ${{ matrix.target }} --no-default-features

      - name: Find deb artifacts
        run: |
          echo 'Listing created .deb artifacts:'
          find target -type f -name "*.deb" -print || true

      - name: Get version
        shell: bash
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload built .deb artifacts
        uses: actions/upload-artifact@v5
        with:
          name: rgrc-${{ env.VERSION }}-${{ matrix.target }}.deb
          path: |
            target/debian/*.deb

